# Generated by Django 4.1.7 on 2023-02-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanName', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
            ],
        ),
    ]
