# Generated by Django 4.1.7 on 2023-02-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scanName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='target',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
