# Generated by Django 4.1.7 on 2023-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_alter_scan_description_alter_scan_scanname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='schedule',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
