# Generated by Django 4.1.7 on 2023-04-06 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_alter_scan_date_alter_scan_description_and_more'),
        ('coordinator', '0006_scan_email_alter_scan_date_alter_scan_description_and_more'),
    ]

    operations = [
    ]
