# Generated by Django 4.1.7 on 2023-04-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0007_merge_20230406_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scan',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
