# Generated by Django 4.1.7 on 2023-04-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0007_merge_20230406_1004'),
        ('coordinator', '0008_alter_scan_description_alter_scan_email'),
    ]

    operations = [
    ]
